### ISSUE TITLE
Missing items since Steam API change

### ISSUE THREAD

**Issue by Wiethoofd** [mohd-akram/item.tf#3]
Valve [changed](https://github.com/SteamDatabase/SteamTracking/commit/e71a1cd100dc7f35f3f26e94f1bf58e6ce9957c4) the API endpoints for the item schema, causing `GetSchema` to become obsolete.
https://github.com/mohd-akram/item.tf/blob/526f761bba88aff0fced027dafe6ad75ed858951/tf2api.py#L18

Item attributes can now be found with the `GetSchemaOverview` and items can be requested per 1000 from the `GetSchemaItems` API endpoint (info about those [here](https://github.com/SteamDatabase/SteamTracking/blob/f146f06bd549abe6e60236d15423cdf6b58aa217/API/IEconItems_440.json#L31-L61)).

Because of this change there have been no new items added since February when the GetSchema started returning empty responses.

**Comment by mohd-akram** [comment]
Thank you for notifying me! I had emailed Valve about the request timing out, but got no response. Did they announce it anywhere?

**Comment by mohd-akram** [comment]
Fixed.

**Comment by Wiethoofd** [comment]
No official announcement, but I had issues with the empty responses too and then got notified of [this post](https://www.reddit.com/r/tf2/comments/8glw2m/website_operators_and_update_enthusiasts_that/).

**Comment by mohd-akram** [comment]
Communication has never been Valve's strongest suit.
