### ISSUE TITLE
Missing images in Chrome

### ISSUE THREAD

**Issue by Wiethoofd** [mohd-akram/item.tf#6]
When looking up items in Chrome the images for them won't show up and console is throwing the following errors:
```
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
Mixed Content: The page at 'https://item.tf/search?q=hat' was loaded over HTTPS,
 but requested an insecure element 'http://media.steampowered.com/apps/440/icons/<imagename>.png'.
 This request was automatically upgraded to HTTPS.
 For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
```
Chrome doesn't allow mixed content on secure pages anymore [since version 84](https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html), and the http**s** version of the item images doesn't exist (invalid certificate).

**Comment by mohd-akram** [comment]
I couldn't actually reproduce this. What version are you on? I only get a warning on Chromium 86.0.4240.75:

```
Mixed Content: The page at 'https://item.tf/' was loaded over HTTPS, but requested an insecure image 'http://media.steampowered.com/apps/tf2/btn_buynow.png'. This content should also be served over HTTPS.
```

Thanks for the heads up either way, this is fixed in da6147f23947b39607665b36793b1fdfbf2f4101.
