### ISSUE TITLE
item.tf website 502 Bad Gateway

### ISSUE THREAD

**Issue by Wiethoofd** [mohd-akram/item.tf#7]
Looks like [item.tf](https://item.tf) is currently throwing a `502 Bad Gateway` error

**Comment by mohd-akram** [comment]
Yeah, was just doing some maintenance, sorry about that.

**Comment by Wiethoofd** [comment]
Ah, just unlucky timing on my end trying to use the site then.

Should be turning this in a feature request for a maintenance page.

**Comment by mohd-akram** [comment]
Ah haha. That wouldn't be much help in this scenario because I was restarting the server a few times. On the plus side, I think the site is faster now after the upgrade I did.
